ALTER TABLE DOKUMENT
  ADD ARKIV_FILTYPE VARCHAR2(100);

ALTER TABLE DOKUMENT
  ADD KL_ARKIV_FILTYPE VARCHAR(100) GENERATED ALWAYS AS ('ARKIV_FILTYPE') VIRTUAL;
ALTER TABLE DOKUMENT
  ADD CONSTRAINT FK_MOTTATT_DOKUMENT_02 FOREIGN KEY (ARKIV_FILTYPE, KL_ARKIV_FILTYPE) REFERENCES KODELISTE (kode, kodeverk);

--datamigrering
UPDATE DOKUMENT
SET ARKIV_FILTYPE = 'PDF'
WHERE CONTENT_TYPE LIKE '%pdf%';

UPDATE DOKUMENT
SET ARKIV_FILTYPE = 'XML'
WHERE CONTENT_TYPE LIKE '%xml%';

ALTER TABLE DOKUMENT
  DROP COLUMN CONTENT_TYPE;