INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, SPRAK, GYLDIG_FOM, GYLDIG_TOM, OPPRETTET_AV, OPPRETTET_TID)
VALUES (seq_kodeliste.nextval, 'DOKUMENT_TYPE_ID', 'SØKNAD_SVANGERSKAPSPENGER', 'I000001', 'Søknad om svangerskapspenger',
        'NB', to_date('01.07.2006', 'DD.MM.RRRR'),
        to_date('31.12.9999', 'DD.MM.RRRR'), 'VL', sysdate);

UPDATE DOKUMENT
SET DOKUMENT_TYPE_ID = 'SØKNAD_SVANGERSKAPSPENGER'
WHERE DOKUMENT_TYPE_ID = 'SØKNAD_SVANGERSKAPSPENGER_SELVSTENDIG';

DELETE FROM KODELISTE WHERE KODEVERK = 'DOKUMENT_TYPE_ID' AND KODE = 'SØKNAD_SVANGERSKAPSPENGER_SELVSTENDIG';