UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000112',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000110'
  AND KODE = 'DOKUMENTASJON_INTRODUKSJONSPROGRAM';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000111',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000109'
  AND KODE = 'BEGRUNNELSE_SØKNAD_ETTERSKUDD';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000110',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000108'
  AND KODE = 'DOKUMENTASJON_ALENEOMSORG';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000109',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000107'
  AND KODE = 'SKJEMA_TILRETTELEGGING_OMPLASSERING';