UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000112',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000110'
  AND KODE = 'DOKUMENTASJON_INTRODUKSJONSPROGRAM';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000111',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000109'
  AND KODE = 'BEGRUNNELSE_SØKNAD_ETTERSKUDD';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000110',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000108'
  AND KODE = 'DOKUMENTASJON_ALENEOMSORG';

UPDATE KODELISTE
SET OFFISIELL_KODE = 'I000109',
    ENDRET_AV      = 'VL',
    ENDRET_TID     = sysdate
WHERE OFFISIELL_KODE = 'I000107'
  AND KODE = 'SKJEMA_TILRETTELEGGING_OMPLASSERING';

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, SPRAK, GYLDIG_FOM, GYLDIG_TOM, OPPRETTET_AV, OPPRETTET_TID)
VALUES (seq_kodeliste.nextval, 'DOKUMENT_TYPE_ID', 'VURDERING_ARBEID_SYKEMELDING', 'I000107', 'Vurdering av arbeidsmulighet/sykmelding',
        'NB', to_date('21.08.2019', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'), 'VL', sysdate);

INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, NAVN, SPRAK, GYLDIG_FOM, GYLDIG_TOM, OPPRETTET_AV, OPPRETTET_TID)
VALUES (seq_kodeliste.nextval, 'DOKUMENT_TYPE_ID', 'OPPLYSNING_TILRETTELEGGING_SVANGER', 'I000108', 'Opplysninger om muligheter og behov for tilrettelegging ved svangerskap',
        'NB', to_date('21.08.2019', 'DD.MM.RRRR'), to_date('31.12.9999', 'DD.MM.RRRR'), 'VL', sysdate);
