kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpfordel
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger

spec:
  image:  {{image}}
  port: 8080
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  liveness:
    path: /fpfordel/internal/health/isAlive
    port: 8080
    initialDelay: 45
    periodSeconds: 10
    failureThreshold: 27
    timeout: 3
  preStopHookPath: /fpfordel/internal/health/preStop
  prometheus:
    enabled: true
    path: /fpfordel/internal/metrics/prometheus
  readiness:
    path: /fpfordel/internal/health/isReady
    port: 8080
    initialDelay: 45
    periodSeconds: 10
    failureThreshold: 27
    timeout: 3
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
    - kvPath: {{oraclecredskv}}
      mountPath: /var/run/secrets/nais.io/defaultDS
    - kvPath: {{oracleconfigkv}}
      mountPath: /var/run/secrets/nais.io/defaultDSconfig
    - kvPath: {{serviceuserkv}}
      mountPath: /var/run/secrets/nais.io/serviceuser
    - kvPath: /apikey/appdynamics/{{environment}}
      mountPath: /var/run/secrets/nais.io/appdynamics
  env:
{{#each env}}
   - name: {{@key}}
     value: "{{this}}"
{{/each}}
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  kafka:
    pool: {{kafkaPool}}
  accessPolicy:
    inbound:
      rules:
        - application: fpsoknad-mottak
