kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: fpfordel
  namespace: {{namespace}}
  labels:
    team: teamforeldrepenger
spec:
  image:  {{image}}
  ingresses:
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  liveness:
    path: fpfordel/internal/health/isAlive
    port: 8080
    initialDelay: 45
    periodSeconds: 10
    failureThreshold: 30
    timeout: 1
  port: 8080
  preStopHookPath: fpfordel/internal/health/preStop
  prometheus:
    enabled: true
    path: fpfordel/internal/prometheus
  readiness:
    path: fpfordel/internal/health/isReady
    port: 8080
    initialDelay: 45
    timeout: 1
  replicas:
{{#if minReplicas}}
    min: {{minReplicas}}
{{else}}
    min: 2
{{/if}}
{{#if maxReplicas}}
    min: {{maxReplicas}}
{{else}}
    max: 2
{{/if}} 
    cpuThresholdPercentage: 80
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 1024Mi
  vault:
    enabled: true
    paths:
    - kvPath: {{oraclecredskv}}
      mountPath: /var/run/secrets/nais.io/defaultDS
    - kvPath: {{oracleconfigkv}}
      mountPath: /var/run/secrets/nais.io/defaultDSconfig   
    - kvPath: {{serviceuserkv}}
      mountPath: /var/run/secrets/nais.io/srvfpfordel
    - kvPath: /kv/{{cluster}}/fss/fpfordel/{{namespace}}
      mountPath: /var/run/secrets/nais.io/vault
  env: 
{{#each env}}
   - name: {{@key}}
     value: "{{this}}"
{{/each}}    
