DROP SEQUENCE SEQ_KODELISTE ;

CREATE SEQUENCE  "SEQ_JOURNALPOST"  MINVALUE 1  INCREMENT BY 50 START WITH 1 NOCACHE NOCYCLE ;

CREATE TABLE "JOURNALPOST"
(	"ID" NUMBER(19,0) NOT NULL,
     "JOURNALPOST_ID" VARCHAR2(32 CHAR) NOT NULL,
     "TILSTAND" VARCHAR2(12 CHAR),
     "KANAL" VARCHAR2(16 CHAR),
     "REFERANSE" VARCHAR2(64 CHAR),
     "OPPRETTET_AV" VARCHAR2(20 CHAR) DEFAULT 'VL' NOT NULL ,
     "OPPRETTET_TID" TIMESTAMP (3) DEFAULT systimestamp NOT NULL
) ;

COMMENT ON TABLE "JOURNALPOST"  IS 'Metadataene til dokumentene som fordeles';
COMMENT ON COLUMN "JOURNALPOST"."ID" IS 'Primærnøkkel';
COMMENT ON COLUMN "JOURNALPOST"."JOURNALPOST_ID" IS 'ID til journalposten i JOARK';
COMMENT ON COLUMN "JOURNALPOST"."TILSTAND" IS 'Journalpostens tilstand';
COMMENT ON COLUMN "JOURNALPOST"."KANAL" IS 'Innsendingskanal';
COMMENT ON COLUMN "JOURNALPOST"."REFERANSE" IS 'Unik referanse fra kanal';

CREATE UNIQUE INDEX "PK_JOURNALPOST" ON "JOURNALPOST" ("ID");
ALTER TABLE "JOURNALPOST" ADD CONSTRAINT "PK_JOURNALPOST" PRIMARY KEY ("ID")
    USING INDEX  ENABLE;

CREATE INDEX "IDX_JOURNALPOST_ID" ON "JOURNALPOST" ("JOURNALPOST_ID") ;
