Insert into KODELISTE (ID,KODEVERK,KODE,OFFISIELL_KODE,NAVN,BESKRIVELSE,SPRAK,GYLDIG_FOM,GYLDIG_TOM)
values (SEQ_KODELISTE.nextval,'DOKUMENT_TYPE_ID','TILBAKEKREV_UTTALELSE','I000114','Uttalelse tilbakekreving',null,'NB',
        to_date('04.09.2019','DD.MM.RRRR'),to_date('31.12.9999','DD.MM.RRRR'));
