CREATE TABLE "KONFIG_VERDI"
(
  "ID"                   NUMBER(19, 0),
  "KONFIG_KODE"          VARCHAR2(50 CHAR),
  "KONFIG_GRUPPE"        VARCHAR2(50 CHAR),
  "KONFIG_VERDI"         VARCHAR2(255 CHAR),
  "GYLDIG_FOM"           DATE              DEFAULT sysdate,
  "GYLDIG_TOM"           DATE              DEFAULT to_date('31.12.9999', 'dd.mm.yyyy'),
  "OPPRETTET_AV"         VARCHAR2(20 CHAR) DEFAULT 'VL',
  "OPPRETTET_TID"        TIMESTAMP(3)      DEFAULT systimestamp,
  "ENDRET_AV"            VARCHAR2(20 CHAR),
  "ENDRET_TID"           TIMESTAMP(3),
  KL_KONFIG_VERDI_GRUPPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KONFIG_VERDI_GRUPPE') VIRTUAL NOT NULL,
  CONSTRAINT FK_KONFIG_VERDI_1 FOREIGN KEY ("KONFIG_GRUPPE", "KL_KONFIG_VERDI_GRUPPE") REFERENCES KODELISTE ("KODE", "KODEVERK")
);

CREATE SEQUENCE "SEQ_KONFIG_VERDI" MINVALUE 1000000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 50 START WITH 1001200 NOCACHE NOORDER NOCYCLE;

COMMENT ON COLUMN "KONFIG_VERDI"."ID" IS 'Primary Key';
COMMENT ON COLUMN "KONFIG_VERDI"."KONFIG_KODE" IS 'Angir kode som identifiserer en konfigurerbar verdi. ';
COMMENT ON COLUMN "KONFIG_VERDI"."KONFIG_GRUPPE" IS 'Angir gruppe en konfigurerbar verdi kode tilhører (hvis noen - kan også spesifiseres som INGEN).';
COMMENT ON COLUMN "KONFIG_VERDI"."KONFIG_VERDI" IS 'Angir verdi';
COMMENT ON COLUMN "KONFIG_VERDI"."GYLDIG_FOM" IS 'Gydlig fra-og-med dato';
COMMENT ON COLUMN "KONFIG_VERDI"."GYLDIG_TOM" IS 'Gydlig til-og-med dato';
COMMENT ON TABLE "KONFIG_VERDI" IS 'Angir konfigurerbare verdier med kode, eventuelt tilhørende gruppe.';

CREATE TABLE "KONFIG_VERDI_KODE"
(
  "KODE"                 VARCHAR2(50 CHAR),
  "KONFIG_GRUPPE"        VARCHAR2(100 CHAR) DEFAULT 'INGEN',
  "NAVN"                 VARCHAR2(50 CHAR),
  "KONFIG_TYPE"          VARCHAR2(100 CHAR),
  "BESKRIVELSE"          VARCHAR2(255 CHAR),
  "OPPRETTET_AV"         VARCHAR2(20 CHAR)  DEFAULT 'VL',
  "OPPRETTET_TID"        TIMESTAMP(3)       DEFAULT systimestamp,
  "ENDRET_AV"            VARCHAR2(20 CHAR),
  "ENDRET_TID"           TIMESTAMP(3),
  KL_KONFIG_VERDI_GRUPPE VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KONFIG_VERDI_GRUPPE') VIRTUAL NOT NULL,
  KL_KONFIG_VERDI_TYPE   VARCHAR2(100 CHAR) GENERATED ALWAYS AS ('KONFIG_VERDI_TYPE') VIRTUAL   NOT NULL,
  CONSTRAINT FK_KONFIG_VERDI_KODE_82 FOREIGN KEY ("KONFIG_GRUPPE", "KL_KONFIG_VERDI_GRUPPE") REFERENCES KODELISTE ("KODE", "KODEVERK"),
  CONSTRAINT FK_KONFIG_VERDI_KODE_83 FOREIGN KEY ("KONFIG_TYPE", "KL_KONFIG_VERDI_TYPE") REFERENCES KODELISTE ("KODE", "KODEVERK")
);

COMMENT ON COLUMN "KONFIG_VERDI_KODE"."KODE" IS 'Primary Key';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."KONFIG_GRUPPE" IS 'Angir gruppe en konfigurerbar verdi kode tilhører (hvis noen - kan også spesifiseres som INGEN).';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."NAVN" IS 'Angir et visningsnavn';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."KONFIG_TYPE" IS 'Type angivelse for koden';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."BESKRIVELSE" IS 'Beskrivelse av formÃ¥let den konfigurerbare verdien';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."KL_KONFIG_VERDI_TYPE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON COLUMN "KONFIG_VERDI_KODE"."KL_KONFIG_VERDI_GRUPPE" IS 'Referanse til KODEVERK-kolonnen i KODELISTE-tabellen';
COMMENT ON TABLE "KONFIG_VERDI_KODE" IS 'Angir unik kode for en konfigurerbar verdi for validering og utlisting av tilgjengelige koder.';


CREATE UNIQUE INDEX "PK_KONFIG_VERDI"
  ON "KONFIG_VERDI" ("ID");
CREATE INDEX "IDX_KONFIG_VERDI_1"
  ON "KONFIG_VERDI" ("GYLDIG_FOM", "GYLDIG_TOM");
CREATE INDEX "IDX_KONFIG_VERDI_3"
  ON "KONFIG_VERDI" ("KONFIG_KODE");
CREATE INDEX "IDX_KONFIG_VERDI_2"
  ON "KONFIG_VERDI" ("KONFIG_GRUPPE");
CREATE UNIQUE INDEX "UIDX_KONFIG_VERDI_1"
  ON "KONFIG_VERDI" ("KONFIG_GRUPPE", "GYLDIG_TOM", "KONFIG_KODE");

ALTER TABLE "KONFIG_VERDI"
  ADD CONSTRAINT "PK_KONFIG_VERDI" PRIMARY KEY ("ID") ENABLE;
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("OPPRETTET_TID" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("OPPRETTET_AV" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("GYLDIG_TOM" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("GYLDIG_FOM" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("KONFIG_GRUPPE" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("KONFIG_KODE" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI"
  MODIFY ("ID" NOT NULL ENABLE);


CREATE UNIQUE INDEX "PK_KONFIG_VERDI_KODE"
  ON "KONFIG_VERDI_KODE" ("KODE", "KONFIG_GRUPPE");

ALTER TABLE "KONFIG_VERDI_KODE"
  ADD CONSTRAINT "PK_KONFIG_VERDI_KODE" PRIMARY KEY ("KODE", "KONFIG_GRUPPE") ENABLE;
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("OPPRETTET_TID" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("OPPRETTET_AV" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("KONFIG_TYPE" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("NAVN" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("KONFIG_GRUPPE" NOT NULL ENABLE);
ALTER TABLE "KONFIG_VERDI_KODE"
  MODIFY ("KODE" NOT NULL ENABLE);